### ISSUE TITLE
Admin Issue while installing Scandi pwa theme

### ISSUE THREAD

**Issue by jeenapwa** [scandipwa/installer#10]
We have followed the video and installed PWA theme .(https://www.youtube.com/watch?v=g9TgN0o_MjE)

Successfully installed the front end but can't access the admin panel. It showing 404 not found.

![scadnyadmin](https://user-images.githubusercontent.com/57623889/68662029-02cacb00-0562-11ea-886c-15bc2c8d99b0.png)

**Comment by eli-l** [comment]
This is not an installer issue. Judjing by the screenshot - Magento is executing userland controller, instead of admin. You should double check your Magento configuration.

**Comment by jeenapwa** [comment]
What you mean by userland  controller?

**Comment by eli-l** [comment]
magento frontend area

**Comment by jeenapwa** [comment]
Thanks for the reply.

We have tried to install the PWA theme using docker set up by following 
this tutorial https://github.com/scandipwa/scandipwa-base and 
successfully loaded the demo. But couldn't load the admin URL in browser 
though it showing message as
"Admin URL : admin" .

How can we access the admin URL and it showing 404 error whiel taking 
http://scandipwa.local/admin

**Comment by eli-l** [comment]
Have you tried it w/o docker before? Might be service worker cache, try disabling it/using postman, curl etc to reach that resource. Check whether you still get an appshell instead of admin login.

**Comment by jeenapwa** [comment]
We have followed this tutorial 
https://github.com/scandipwa/scandipwa-base
and found configuration in .application file.
We tried to  set up with same credentials but couldn't load admin 
section.

Please help!

**Comment by jeenapwa** [comment]
First we want to know how  will be the admin URL. That not specifying in 
any video and terminal we got response like ADMIN URI: admin.

How we can access it?

**Comment by swathy-sagar** [comment]
Hi, I would like to know if we can make Rest API calls in scandi PWA like in other react apps using fetch
