### ISSUE TITLE
Cannot install graphql

### ISSUE THREAD

**Issue by ldule** [scandipwa/installer#11]
I used installer and followed the steps. Everything went fine. I wanted to test it with data. But after importing sql and unpacking media files I figured out that I have this theme installed: https://demo.scandipwa.com/
but sql dump and media from this repo readme are for this theme: https://v1.scandipwa.com/
I found media files for https://demo.scandipwa.com/ but couldn't find sql dump for that version of demo.
My frontend is not working, I have just header and footer on homepage. Nothing else.
Do I have old version of theme installed or where did I make mistake?

Thanks

**Comment by ldule** [comment]
I've managed to find sql dump for my version. But now new issue appeared. Only menu is working. Getting error: Error fetching Product list.
I think that the problem is probably graphql so i tried to install it but getting this error:
 Problem 1
    - Installation request for scandipwa/graphql ^1.0 -> satisfiable by scandipwa/graphql[1.0.0].
    - scandipwa/graphql 1.0.0 requires magento/product-community-edition 2.3.0 -> satisfiable by magento/product-community-edition[2.3.0] but these conflict with your requirements or minimum-stability.

I'm using magento 2.3.4 version.

**Comment by eli-l** [comment]
Magento 2.3.4 support is not yet confirmed.
This issue is not an issue with installer itself, use https://github.com/scandipwa/base-theme instead.
