### ISSUE TITLE
I need support in Magento 2.3.4

### ISSUE THREAD

**Issue by Dhar114** [scandipwa/installer#12]
![Screenshot_3](https://user-images.githubusercontent.com/25716285/79695215-363d1e80-8293-11ea-9c51-cb2752ebfabc.png)
I need support in Magento 2.3.4, I need to integrate PWA in my Magento 2.3.4, Let me know if you can help me.

**Comment by alfredsgenkins** [comment]
Sorry, M2.3.4 is not supported, we skipped it. Only Magento 2.3.5
