### ISSUE TITLE
magento/magento2-base no matching package found

### ISSUE THREAD

**Issue by v-bansal** [scandipwa/installer#14]
Please update the installer package

**Comment by yeegor** [comment]
Please provide the exact error from console and your composer.json.

**Comment by WaysonWei** [comment]
Fresh Magento 2.3.5 installed. Run into same problem here. 

`root@ks-allinone:/var/www/html/magento2# composer require scandipwa/installer
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^3.0 for scandipwa/installer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for scandipwa/installer ^3.0 -> satisfiable by scandipwa/installer[3.0.0].
    - scandipwa/installer 3.0.0 requires magento/magento2-base ^2.3.3 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
root@ks-allinone:/var/www/html/magento2#`
