### ISSUE TITLE
No theme compilation step present in docs

### ISSUE THREAD

**Issue by 0m3r** [scandipwa/installer#4]
I followed your installation [instruction](https://github.com/scandipwa/installer#usage).
but the theme does not appear.

![Знімок екрану з 2019-06-13 14-39-50](https://user-images.githubusercontent.com/412612/59429778-2b9b3880-8de9-11e9-9f66-ae04b4a8b55a.png)

In filesystem 
![Знімок екрану з 2019-06-13 14-27-59](https://user-images.githubusercontent.com/412612/59429021-7caa2d00-8de7-11e9-8af7-2a5b40b9baee.png)
In database 
![Знімок екрану з 2019-06-13 14-26-43](https://user-images.githubusercontent.com/412612/59429022-7d42c380-8de7-11e9-802e-04e0c8f804c4.png)

**Comment by eli-l** [comment]
Hi @0m3r 
please run `php bin/magento setup:upgrade`

**Comment by 0m3r** [comment]
theme(s) type 4 was filtered
 
Magento\Theme\Model\ResourceModel\Theme\Collection.php 

~~~php
  /**
     * Filter visible themes in backend (physical and virtual only)
     *
     * @return $this
     */
    public function filterVisibleThemes()
    {
        $this->addTypeFilter(
            [
                \Magento\Framework\View\Design\ThemeInterface::TYPE_PHYSICAL,
                \Magento\Framework\View\Design\ThemeInterface::TYPE_VIRTUAL,
            ]
        );
        return $this;
    }
~~~


~~~sql
SELECT `main_table`.* FROM `theme` AS `main_table` WHERE (`main_table`.`type` IN(0, 1)) AND (main_table.area='frontend'
~~~

**Comment by 0m3r** [comment]
Ok. My failure.

What minimum list of scandipwa modules I must enable before? 
~~~
php bin/magento setup:upgrade
~~~
~~~
List of disabled modules:
...
ScandiPWA_CatalogGraphQl
ScandiPWA_CmsGraphQl
ScandiPWA_CustomerGraphQl
Scandiweb_Core
ScandiPWA_PersistedQuery
ScandiPWA_QuoteGraphQl
ScandiPWA_Route717
Scandiweb_Slider
ScandiPWA_Source
ScandiPWA_UrlrewriteGraphQl
ScandiPWA_WishlistGraphQl
ScandiPWA_MenuOrganizer
Scandiweb_LocaleResolverFix
ScandiPWA_SliderGraphQl

~~~
Add something 
~~~bash 
php bin/magento module:enable $(php bin/magento module:status | grep Scandi)
~~~
to Readme

**Comment by 0m3r** [comment]
I enable all Scandi modules (expect ScandiPWA_PersistedQuery) 
run 
~~~
 bin/magento setup:upgrade 
~~~
re-run 
~~~
 bin/magento scandipwa:theme:bootstrap Scandiweb/pwa
~~~
but still doesn't see scandipwa theme in theme grid

**Comment by alfredsgenkins** [comment]
Theme must be compiled. If there is no `Magento_Theme` folder, nothing will happen. To compile a theme, run `npm ci` from theme dir, run `npm run build`. Is this mentioned in our instructions?

**Comment by alfredsgenkins** [comment]
Quick question: what's behind the decision to disable persisted query? I think it is one of composer requirements for the theme to run properly. Are you not using Varnish?

**Comment by alfredsgenkins** [comment]
The doc must be updated. It seems like no theme compilation instructions where added. I will rename this issue to docs missing.

**Comment by eli-l** [comment]
Readme updated as v1.3.1

**Comment by 0m3r** [comment]
I have built the theme.
 
https://github.com/scandipwa/scandipwa-base/blob/master/deploy/start.sh#L58

![Знімок екрану з 2019-06-14 10-12-00](https://user-images.githubusercontent.com/412612/59490279-e6304700-8e8c-11e9-8b60-8fb66a8ea7e2.png)

I also ran 
~~~
bin/magento setup:di:compile
bin/magento setup:static-content:deploy -f
bin/magento cache:flush
~~~
etc.

What is the next step? 
The theme still no in the list. So I can't apply it.
Do you see it in your backend ?

Content -> Design -> Themes

**Comment by eli-l** [comment]
@0m3r 
Now I get what is the issue. Hold on, we'll fix it shortly.
For now you can edit theme value directly in your DB.
