### ISSUE TITLE
Theme is not visible in admin panel

### ISSUE THREAD

**Issue by eli-l** [scandipwa/installer#5]
Related #4

**Comment by 0m3r** [comment]
I added 4 to the filter conditions. 
You will need to add a minimum of two plugins.

Magento\Theme\Model\ResourceModel\Theme\Collection.php
filterVisibleThemes()
https://github.com/scandipwa/installer/issues/4#issuecomment-501696795

Magento\Theme\Ui\Component\Theme\DataProvider.php 
_initSelect()

**Comment by eli-l** [comment]
You are always welcome to open a Pull Request.

**Comment by eli-l** [comment]
Solved in release v1.3.2
