### ISSUE TITLE
Composer issue while installing theme in magento 2.3.3

### ISSUE THREAD

**Issue by jithinnjose** [scandipwa/installer#9]
composer require scandipwa/installer
Using version ^1.6 for scandipwa/installer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for scandipwa/installer ^1.6 -> satisfiable by scandipwa/installer[1.6.0, 1.6.1].
    - Can only install one of: magento/composer[1.4.0, 1.5.0].
    - Can only install one of: magento/composer[1.5.0, 1.4.0].
    - Conclusion: install magento/composer 1.4.0
    - Installation request for magento/composer (installed at 1.5.0) -> satisfiable by magento/composer[1.5.0].

**Comment by alfredsgenkins** [comment]
Can you please specify exact commands you used? Sequence ideally.

We have never seen this issue inside our docker-based setup. I assume you are not using it?

**Comment by jithinnjose** [comment]
Command I used is
composer require scandipwa/installer
Is there anything else need to do before this?

**Comment by jeenapwa** [comment]
We have tried to install the PWA theme using docker set up by following this tutorial https://github.com/scandipwa/scandipwa-base   and successfully loaded the demo. But couldn't load the admin URL in browser though it showing  message as
"Admin  URL : admin"  .

Our demo URL is http://localhost:our port number.(Ex: http://localhost:3000)
How can we access the admin URL?

**Comment by alfredsgenkins** [comment]
Please add entry in your /etc/hosts and map 127.0.0.1 to scandipwa.local. then visit scandipwa.local The port you are trying to access is Frontend container port, not the application (Magento) itself.

**Comment by jeenapwa** [comment]
We can access the front end(site loading) but not getting admin side.

**Comment by alfredsgenkins** [comment]
Please see response above. I wrote that 3000 is not Magento port. Main nginx is serving on 80 and 443

**Comment by alfredsgenkins** [comment]
But Magento will redirect you to ScandiPWA.local

**Comment by alfredsgenkins** [comment]
Follow along this video: https://www.youtube.com/watch?v=g9TgN0o_MjE

**Comment by jeenapwa** [comment]
We have followed the same video and installed PWA theme .(https://www.youtube.com/watch?v=g9TgN0o_MjE)
![scandy-frontend](https://user-images.githubusercontent.com/57623889/68641358-94214980-0530-11ea-8020-7b3fd655b5cb.png)

The issue we facing is how we can log into ADMIN PANEL and please provide us the steps to access the ADMIN URL so that we can move further. ie http://ScandiPWA.local/admin  getting not found.

**Comment by alfredsgenkins** [comment]
For what reason are you trying to access 8080 port on a screenshot? The exact url you typed in must work.

**Comment by alfredsgenkins** [comment]
If you have a /etc/hosts mapping, you won't need a port in the url. Verify you have it. Make sure you can access the website without a port. Then it will work :)

**Comment by jeenapwa** [comment]
So without port can we access the admin URL?

**Comment by alfredsgenkins** [comment]
Yes

**Comment by jeenapwa** [comment]
If so can you provide the admin panel screenshot or admin URL how you accessing it?

**Comment by jeenapwa** [comment]
But the magento code not in doc root...it is coming under src folder.

**Comment by alfredsgenkins** [comment]
I won't prove you anything, I am on the phone currently, and I am not supposed to. Can you just go to the http://scandipwa.local/admin and it will be there if you specified it in hosts. Before this make sure to check http://scandipwa.local it must return you the theme.

**Comment by jeenapwa** [comment]
So you saying we can access the admin panel like this ? http://scandipwa.local/admin 
Do we need to change  root to ./pub folder ?

**Comment by alfredsgenkins** [comment]
The nginx serves you Magento from any folder you specify, the location of Magento installation does not matter, plus if you check were it is mapped in container it will be /var/www/public to do it, Google how to execute the docker-compose service and execute app container.

**Comment by alfredsgenkins** [comment]
Yes, I am saying exactly this. You do not need to change anything.

**Comment by jeenapwa** [comment]
Okay, Thanks let me try

**Comment by jeenapwa** [comment]
We tried to set up PWA theme using https://libraries.io/packagist/scandipwa%2Finstaller

and getting error >>composer require scandipwa/installer
Using version ^1.6 for scandipwa/installer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Installation request for scandipwa/installer ^1.6 -> satisfiable by scandipwa/installer[1.6.0, 1.6.1].
- Can only install one of: magento/composer[1.4.0, 1.5.0].
- Can only install one of: magento/composer[1.5.0, 1.4.0].
- Conclusion: install magento/composer 1.4.0
- Installation request for magento/composer (installed at 1.5.0) -> satisfiable by magento/composer[1.5.0].

Can't we set up without docker?

**Comment by alfredsgenkins** [comment]
The title of this issue states: Composer issue while installing theme in magento 2.3.3.
Please wait. Today will be the 2.3.3 release support

**Comment by eli-l** [comment]
2.3.3 support has been delayed. Please follow-up next releases.

**Comment by jeenapwa** [comment]
Hi Ilja Lapkovskis  ,
We couldn't find any section regarding admin side in that video. (https://www.youtube.com/watch?v=g9TgN0o_MjE)
Please help!
